# This file provides instructions for packaging.

`MooseX-ConstructInstance`
	deps:test-requirement    [ deps:on "Test::More 0.96"^^deps:CpanId ];
	deps:runtime-requirement [ deps:on "perl 5.008"^^deps:CpanId ];
	deps:runtime-requirement [ deps:on "Moo::Role"^^deps:CpanId ];
	deps:runtime-suggestion  [ deps:on "Moose 2.0000"^^deps:CpanId ];
	deps:runtime-suggestion  [ deps:on "MooseX::RelatedClasses"^^deps:CpanId ].

